name: CI

on: [pull, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
      run: |
        java -version
        javac -version
        javac *.java
  testMapMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
      run: |
        javac -cp "junit-4.10.jar:." *.java
        java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestMapMove
  testGhostValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
      run: |
        javac -cp "junit-4.10.jar:." *.java
        java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestGhostValidMoves
  testPacManValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
      run: |
        javac -cp "junit-4.10.jar:." *.java
        java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestPacManValidMoves